# Scala CircleCI 2.0 configuration file
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/node:7.10

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: echo $PATH

      - run: sudo ln -s /usr/bin/nodejs /usr/bin/node

      - run: export PATH="/usr/bin:$PATH"

      - run: echo $PATH

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          key: v1-dependencies--{{ checksum "build.sbt" }}
          paths:
            - ~/.m2

      - run: cat /dev/null | sbt test:test
